//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrytogramDCipher.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrytogramDCipher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a THE
        ///OF
        ///AND
        ///A
        ///TO
        ///IN
        ///IS
        ///BE
        ///THAT
        ///WAS
        ///HE
        ///FOR
        ///IT
        ///WITH
        ///AS
        ///HIS
        ///I
        ///ON
        ///HAVE
        ///AT
        ///BY
        ///NOT
        ///THEY
        ///THIS
        ///HAD
        ///ARE
        ///BUT
        ///FROM
        ///OR
        ///SHE
        ///AN
        ///WHICH
        ///YOU
        ///ONE
        ///WE
        ///ALL
        ///WERE
        ///HER
        ///WOULD
        ///THERE
        ///THEIR
        ///WILL
        ///WHEN
        ///WHO
        ///HIM
        ///BEEN
        ///HAS
        ///MORE
        ///IF
        ///NO
        ///OUT
        ///DO
        ///SO
        ///CAN
        ///WHAT
        ///UP
        ///SAID
        ///ABOUT
        ///OTHER
        ///INTO
        ///THAN
        ///ITS
        ///TIME
        ///ONLY
        ///COULD
        ///NEW
        ///THEM
        ///MAN
        ///SOME
        ///THESE
        ///THEN
        ///TWO
        ///FIRST
        ///MAY
        ///ANY
        ///LIKE
        ///NOW
        ///MY
        ///SUCH
        ///MAKE
        ///OVER
        ///OUR
        ///EVEN
        ///MOST
        ///ME
        ///STATE
        ///AFTER
        ///ALSO
        ///MADE
        ///MANY
        ///DID
        ///MUST
        ///BEFORE
        ///BACK
        ///SEE
        ///THROUG [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string w105 {
            get {
                return ResourceManager.GetString("w105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a the
        ///of
        ///and
        ///to
        ///a
        ///in
        ///for
        ///is
        ///on
        ///that
        ///by
        ///this
        ///with
        ///i
        ///you
        ///it
        ///not
        ///or
        ///be
        ///are
        ///from
        ///at
        ///as
        ///your
        ///all
        ///have
        ///new
        ///more
        ///an
        ///was
        ///we
        ///will
        ///home
        ///can
        ///us
        ///about
        ///if
        ///page
        ///my
        ///has
        ///search
        ///free
        ///but
        ///our
        ///one
        ///other
        ///do
        ///no
        ///information
        ///time
        ///they
        ///site
        ///he
        ///up
        ///may
        ///what
        ///which
        ///their
        ///news
        ///out
        ///use
        ///any
        ///there
        ///see
        ///only
        ///so
        ///his
        ///when
        ///contact
        ///here
        ///business
        ///who
        ///web
        ///also
        ///now
        ///help
        ///get
        ///pm
        ///view
        ///online
        ///c
        ///e
        ///first
        ///am
        ///been
        ///would
        ///how
        ///were
        ///me
        ///s
        ///services
        ///some
        ///these
        ///click
        ///its
        ///like
        ///service
        ///x
        ///than
        ///find
        ///price
        ///date
        ///back
        ///top
        ///people
        ///had
        ///list
        ///name
        ///just
        ///over
        ///state
        ///year
        ///day
        ///into [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string w10k {
            get {
                return ResourceManager.GetString("w10k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a the
        ///of
        ///and
        ///to
        ///a
        ///in
        ///for
        ///is
        ///on
        ///that
        ///by
        ///this
        ///with
        ///i
        ///you
        ///it
        ///not
        ///or
        ///be
        ///are
        ///from
        ///at
        ///as
        ///your
        ///all
        ///have
        ///new
        ///more
        ///an
        ///was
        ///we
        ///will
        ///home
        ///can
        ///us
        ///about
        ///if
        ///page
        ///my
        ///has
        ///search
        ///free
        ///but
        ///our
        ///one
        ///other
        ///do
        ///no
        ///information
        ///time
        ///they
        ///site
        ///he
        ///up
        ///may
        ///what
        ///which
        ///their
        ///news
        ///out
        ///use
        ///any
        ///there
        ///see
        ///only
        ///so
        ///his
        ///when
        ///contact
        ///here
        ///business
        ///who
        ///web
        ///also
        ///now
        ///help
        ///get
        ///pm
        ///view
        ///online
        ///c
        ///e
        ///first
        ///am
        ///been
        ///would
        ///how
        ///were
        ///me
        ///s
        ///services
        ///some
        ///these
        ///click
        ///its
        ///like
        ///service
        ///x
        ///than
        ///find
        ///price
        ///date
        ///back
        ///top
        ///people
        ///had
        ///list
        ///name
        ///just
        ///over
        ///state
        ///year
        ///day
        ///into [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string w20k {
            get {
                return ResourceManager.GetString("w20k", resourceCulture);
            }
        }
    }
}
